version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8080:8000"  # була зміна порту з 8000 на 8080
    environment:
      - DEBUG=1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"