# Generated by Django 5.0.7 on 2024-08-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_delete_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='description',
        ),
    ]
