# Generated by Django 5.0.7 on 2024-08-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_product_templatetags_product_tags'),
    ]

    operations = [
    ]
