"""
Django settings for ProjectA project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config


import ProjectA


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^##!qrdf-no=oukij@8m&$!de2!*lm619h2@+o0qusi=*z@6al'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #l display detailed error pages

ALLOWED_HOSTS = []
"""is not applied while debug mode is on or when the tests are run. Once you
move your site to production and set DEBUG to False, you will have to add your domain/host
to this setting to allow it to serve your Django site."""

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',         #An administration site.
    'django.contrib.auth',          #An authentication framework.
    'django.contrib.contenttypes',  #A framework for handling content types.
    'django.contrib.sessions',      #A session framework.
    'django.contrib.messages',      #A messaging framework.
    'django.contrib.sites',
    'django.contrib.sitemaps',
    # 'django.contrib.postgres',
    'django.contrib.staticfiles',   #A framework for managing static files, such as CSS,JavaScript files, and images.
    'taggit',
    'rest_framework',               #Django REST framework (DRF)
    'marketplace.apps.MarketplaceConfig',  #marketplace apps
]

MIDDLEWARE = [                                           #middleware to be executed
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProjectA.urls'      # вказує на Python модуль, де визначені кореневі шаблони URL вашого додатка.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'marketplace' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjectA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 'USER': 'admin',        # Ім'я користувача бази даних
        # 'PASSWORD': 'your_password',  # Пароль до бази даних
        # 'HOST': 'localhost',    # Хост бази даних
        # 'PORT': '5432',         # Порт PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nedilja90@gmail.com'
EMAIL_HOST_PASSWORD = 'mxly ehgm ixaw dhjg'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'Marketplace <nedilja90@gmail.com>'

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Або інший брокер повідомлень
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_RESULT_SERIALIZER = 'json'